name: 'Repository Sync Action'
description: 'Synchronize repositories'
author: Your name or organization here

# Add your action's branding here. This will appear on the GitHub Marketplace.
branding:
  icon: heart
  color: red

# Define your inputs here.
inputs:
  secret_config:
    description: 'config'
    required: false
  variable_config:
    description: 'config'
    required: true

# Define your outputs here.
outputs:
  time:
    description: 'The time the action was run'

runs:
  using: 'node20'
  main: 'dist/index.js'
