name: test sync

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *'

permissions:
  contents: read

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Build the action
        run: npm run package

      - name: Run synchronization
        uses: ./
        with:
          #
          source_repository_url_list: ${{ vars.SOURCE_REPOSITORY_URL_LIST }}
          source_repository_username: ${{ secrets.SOURCE_REPOSITORY_USERNAME }}
          source_repository_password: ${{ secrets.SOURCE_REPOSITORY_PASSWORD }}
          #
          target_repository_url_list: ${{ vars.TARGET_REPOSITORY_URL_LIST }}
          target_repository_username: ${{ secrets.TARGET_REPOSITORY_USERNAME }}
          target_repository_password: ${{ secrets.TARGET_REPOSITORY_PASSWORD }}
          #
          target_repository_force_url_list: ${{ vars.TARGET_REPOSITORY_FORCE_URL_LIST }}
          target_repository_not_check_all_branch_url_list: ${{ vars.TARGET_REPOSITORY_NOT_CHECK_ALL_BRANCH_URL_LIST }}
